import React, { useCallback, useEffect, useState } from 'react';
import { Activity, CloudDownload, Cpu, Download, File, Folder, HardDrive, Home, LogOut, Menu, Play, RefreshCw, Search, Server, Settings, Video, X } from 'lucide-react';

type TabKey = 'home' | 'files' | 'media' | 'system';
type ApiEnvelope<T> = { data?: T; error?: { message?: string } };
type MediaItem = { id: number; filename: string; path: string; category: string; mime_type: string; size_human: string; stream_url: string };
type FileItem = { name: string; path: string; is_dir: boolean; size_human?: string; mime_type?: string };
type DownloadTask = { task_id: string; url: string; filename: string; destination: string; status: string; progress_percent: number; downloaded_bytes: number; total_bytes: number; error?: string };
type Metrics = { cpu: { usage_percent: number; physical_cores: number; load_average?: { '1min': number } }; memory: { usage_percent: number; used_human: string; total_human: string; free_human: string }; uptime: { server_uptime_human: string }; operating_system: { hostname: string; distribution: string } };

const API_BASE = (import.meta.env.VITE_API_BASE || (window.location.hostname === 'localhost' ? 'http://localhost:8080' : window.location.origin)).replace(/\/$/, '');
const TOKEN_KEY = 'dhiliphome_token';

function useApi(token: string) {
  return useCallback(async <T,>(path: string, init: RequestInit = {}): Promise<T> => {
    const headers = new Headers(init.headers);
    headers.set('Accept', 'application/json');
    if (token) headers.set('Authorization', `Bearer ${token}`);
    const response = await fetch(`${API_BASE}${path}`, { ...init, headers });
    const body = await response.json().catch(() => ({})) as ApiEnvelope<T>;
    if (!response.ok) throw new Error(body.error?.message || `Request failed (${response.status})`);
    return (body.data === undefined ? body : body.data) as T;
  }, [token]);
}

function streamUrl(item: MediaItem | FileItem, token: string) {
  const path = 'stream_url' in item ? item.stream_url : `/api/media/stream/${item.path}`;
  return `${API_BASE}${path}?token=${encodeURIComponent(token)}`;
}

export default function ClientApp() {
  const [token, setToken] = useState(() => localStorage.getItem(TOKEN_KEY) || '');
  const [tab, setTab] = useState<TabKey>('home');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const api = useApi(token);
  const signIn = async (event: React.FormEvent) => {
    event.preventDefault(); setError('');
    try { const result = await api<{ token: string }>('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); localStorage.setItem(TOKEN_KEY, result.token); setToken(result.token); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in'); }
  };
  const signOut = () => { localStorage.removeItem(TOKEN_KEY); setToken(''); };
  if (!token) return <LoginScreen username={username} password={password} error={error} onUsername={setUsername} onPassword={setPassword} onSubmit={signIn} />;
  return <Shell tab={tab} setTab={setTab} signOut={signOut} token={token} api={api} error={error} onError={setError} />;
}

function LoginScreen({ username, password, error, onUsername, onPassword, onSubmit }: { username: string; password: string; error: string; onUsername: (value: string) => void; onPassword: (value: string) => void; onSubmit: (event: React.FormEvent) => void }) {
  return <main className="login-page"><div className="login-card"><div className="brand-mark"><Server size={25} /></div><p className="eyebrow">DHILIP HOME</p><h1>Your private server</h1><p className="muted">Sign in to manage files, media and system health.</p><form onSubmit={onSubmit}><label>Username<input value={username} onChange={event => onUsername(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={event => onPassword(event.target.value)} required /></label>{error && <p className="error-text">{error}</p>}<button className="primary-button" type="submit">Connect to server</button></form></div></main>;
}

function Shell({ tab, setTab, signOut, token, api, error, onError }: { tab: TabKey; setTab: (tab: TabKey) => void; signOut: () => void; token: string; api: <T>(path: string, init?: RequestInit) => Promise<T>; error: string; onError: (value: string) => void }) {
  const nav = [{ id: 'home' as const, label: 'Home', icon: Home }, { id: 'files' as const, label: 'My Files', icon: Folder }, { id: 'media' as const, label: 'Media', icon: Play }, { id: 'system' as const, label: 'System', icon: Activity }];
  return <div className="app-shell"><aside className="sidebar"><div className="sidebar-brand"><span className="brand-mark small"><Server size={18} /></span><strong>DHILIP HOME</strong></div><nav>{nav.map(item => <button className={tab === item.id ? 'nav-item active' : 'nav-item'} key={item.id} onClick={() => setTab(item.id)}><item.icon size={18} />{item.label}</button>)}</nav><button className="nav-item sidebar-bottom" onClick={signOut}><LogOut size={18} />Sign out</button></aside><main className="main-content"><header className="mobile-header"><button className="icon-button"><Menu size={20} /></button><strong>DHILIP HOME</strong><button className="icon-button" onClick={signOut}><LogOut size={18} /></button></header>{error && <div className="toast error-text">{error}<button onClick={() => onError('')}><X size={15} /></button></div>}{tab === 'home' && <HomeView api={api} onNavigate={setTab} />}{tab === 'files' && <FilesView api={api} token={token} onError={onError} />}{tab === 'media' && <MediaView api={api} token={token} onError={onError} />}{tab === 'system' && <SystemView api={api} />}</main></div>;
}

function PageTitle({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-title"><div><p className="eyebrow">DHILIP HOME</p><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action}</div>; }
function MetricTile({ label, value, sub, icon: Icon, color, percent }: { label: string; value: string; sub: string; icon: React.ElementType; color: string; percent: number; key?: string }) { return <div className="metric-tile"><div className={`tile-icon ${color}`}><Icon size={18} /></div><span className="tile-label">{label}</span><strong>{value}</strong><span className="tile-sub">{sub}</span><div className="progress"><i className={color} style={{ width: `${Math.min(100, percent)}%` }} /></div></div>; }
function QuickCard({ icon: Icon, title, subtitle, color, onClick }: { icon: React.ElementType; title: string; subtitle: string; color: string; onClick: () => void }) { return <button className="quick-card" onClick={onClick}><span className={`tile-icon ${color}`}><Icon size={21} /></span><span><strong>{title}</strong><small>{subtitle}</small></span><span className="arrow">→</span></button>; }

function HomeView({ api, onNavigate }: { api: <T>(path: string, init?: RequestInit) => Promise<T>; onNavigate: (tab: TabKey) => void }) {
  const [server, setServer] = useState<{ hostname: string; os: string } | null>(null); const [metrics, setMetrics] = useState<Metrics | null>(null); const [storage, setStorage] = useState<{ media_storage?: { usage_percent: number; used_human: string; total_human: string; free_human: string } } | null>(null);
  const refresh = useCallback(() => Promise.all([api('/api/server'), api('/api/system'), api('/api/storage')]).then(([serverData, metricsData, storageData]) => { setServer(serverData as typeof server); setMetrics(metricsData as Metrics); setStorage(storageData as typeof storage); }).catch(() => undefined), [api]); useEffect(() => { refresh(); }, [refresh]);
  const stats = [{ label: 'STORAGE', value: storage?.media_storage ? `${storage.media_storage.used_human} / ${storage.media_storage.total_human}` : '--', sub: storage?.media_storage ? `${storage.media_storage.usage_percent}% Used • ${storage.media_storage.free_human} Free` : 'Loading', icon: HardDrive, color: 'cyan', percent: storage?.media_storage?.usage_percent || 0 }, { label: 'MEMORY (RAM)', value: metrics?.memory ? `${metrics.memory.used_human} / ${metrics.memory.total_human}` : '--', sub: metrics?.memory ? `${metrics.memory.usage_percent}% Used • ${metrics.memory.free_human} Free` : 'Loading', icon: Cpu, color: 'green', percent: metrics?.memory.usage_percent || 0 }, { label: 'CPU LOAD', value: metrics ? `${metrics.cpu.usage_percent}% Load` : '--', sub: metrics ? `${metrics.cpu.physical_cores} Cores • ${metrics.cpu.load_average?.['1min'] || 0} (1m)` : 'Loading', icon: Activity, color: 'violet', percent: metrics?.cpu.usage_percent || 0 }, { label: 'SERVER UPTIME', value: metrics?.uptime.server_uptime_human || '--', sub: server?.hostname || 'Connecting', icon: Server, color: 'amber', percent: 100 }];
  return <section><PageTitle title="DHILIP HOME" subtitle={server ? `Connected to ${server.hostname}` : 'Connecting to your server'} action={<button className="icon-button" onClick={refresh} title="Refresh"><RefreshCw size={18} /></button>} /><div className="status-card"><div><span className="status-dot" />{server ? 'ONLINE' : 'CONNECTING'}</div><span>{server?.os || 'DhilipHome Server'}</span></div><div className="section-heading"><h2>System overview</h2><span>Live server status</span></div><div className="metric-grid">{stats.map(stat => <MetricTile key={stat.label} {...stat} />)}</div><div className="section-heading"><h2>Quick access</h2></div><div className="quick-grid"><QuickCard icon={Folder} title="FILES" subtitle="Personal cloud" color="cyan" onClick={() => onNavigate('files')} /><QuickCard icon={Play} title="MEDIA" subtitle="Movies & music" color="violet" onClick={() => onNavigate('media')} /><QuickCard icon={Settings} title="SYSTEM" subtitle="Server diagnostics" color="green" onClick={() => onNavigate('system')} /></div></section>;
}

function MediaView({ api, token, onError }: { api: <T>(path: string, init?: RequestInit) => Promise<T>; token: string; onError: (value: string) => void }) {
  const [items, setItems] = useState<MediaItem[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const load = useCallback(() => api<{ items: MediaItem[] }>('/api/media').then(data => setItems(data.items || [])).catch(err => onError(err instanceof Error ? err.message : 'Media could not load')), [api, onError]); useEffect(() => { load(); }, [load]); const filtered = items.filter(item => (category === 'All' || item.category === category) && item.filename.toLowerCase().includes(query.toLowerCase())); const categories = ['All', ...Array.from(new Set(items.map(item => item.category)))];
  return <section><PageTitle title="Media Library" subtitle="Server-indexed entertainment" action={<button className="icon-button" onClick={load}><RefreshCw size={18} /></button>} /><div className="search-row"><Search size={18} /><input placeholder="Search your library..." value={query} onChange={event => setQuery(event.target.value)} /></div><div className="chips">{categories.map(item => <button className={category === item ? 'chip active' : 'chip'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="section-heading"><h2>{filtered.length} items</h2><span>Only video files open externally</span></div><div className="media-grid">{filtered.map(item => { const isVideo = item.mime_type.startsWith('video/'); return <article className="media-card" key={item.id}><div className="media-art"><Video size={34} />{isVideo && <button className="play-button" onClick={() => window.open(streamUrl(item, token), '_blank', 'noopener,noreferrer')} title="Open video externally"><Play size={18} fill="currentColor" /></button>}</div><strong title={item.filename}>{item.filename}</strong><small>{item.category} • {item.size_human}</small></article>; })}</div>{!filtered.length && <EmptyState label="No media found" detail="Scan or upload media to your DhilipHome server." />}</section>;
}

function FilesView({ api, token, onError }: { api: <T>(path: string, init?: RequestInit) => Promise<T>; token: string; onError: (value: string) => void }) {
  const [path, setPath] = useState(''); const [files, setFiles] = useState<FileItem[]>([]); const [search, setSearch] = useState(''); const [showDownload, setShowDownload] = useState(false); const [tasks, setTasks] = useState<DownloadTask[]>([]); const load = useCallback(() => api<{ directories: FileItem[]; files: FileItem[] }>(`/api/files?path=${encodeURIComponent(path)}`).then(data => setFiles([...(data.directories || []), ...(data.files || [])])).catch(err => onError(err instanceof Error ? err.message : 'Files could not load')), [api, path, onError]); useEffect(() => { load(); }, [load]); useEffect(() => { api<DownloadTask[]>('/api/files/remote-download').then(setTasks).catch(() => undefined); }, [api]); const visible = files.filter(item => item.name.toLowerCase().includes(search.toLowerCase()));
  const openFile = (file: FileItem) => { if (file.is_dir) { setPath(file.path); return; } if (file.mime_type?.startsWith('video/')) window.open(streamUrl(file, token), '_blank', 'noopener,noreferrer'); else window.open(`${API_BASE}/api/files/download?path=${encodeURIComponent(file.path)}&token=${encodeURIComponent(token)}`, '_blank', 'noopener,noreferrer'); };
  return <section><PageTitle title="My Files" subtitle={path || 'Personal cloud storage'} action={<><button className="icon-button" onClick={load}><RefreshCw size={18} /></button><button className="primary-button compact" onClick={() => setShowDownload(true)}><CloudDownload size={16} /> Cloud download</button></>} /><div className="search-row"><Search size={18} /><input placeholder="Search files..." value={search} onChange={event => setSearch(event.target.value)} /></div>{tasks.length > 0 && <DownloadTasks tasks={tasks} api={api} setTasks={setTasks} />}<div className="file-list">{visible.map(file => <button className="file-row" key={file.path} onClick={() => openFile(file)}><span className="file-icon">{file.is_dir ? <Folder size={20} /> : file.mime_type?.startsWith('video/') ? <Video size={20} /> : <File size={20} />}</span><span><strong>{file.name}</strong><small>{file.is_dir ? 'Folder' : file.size_human || file.mime_type}</small></span><span className="file-action">{file.is_dir ? '›' : file.mime_type?.startsWith('video/') ? <Play size={17} /> : <Download size={17} />}</span></button>)}</div>{!visible.length && <EmptyState label="No files found" detail={`The server returned no items for ${path || '/'}.`} />}{showDownload && <CloudDownloadDialog api={api} currentFolder={path} onClose={() => setShowDownload(false)} onStarted={task => setTasks(current => [task, ...current])} onError={onError} />}</section>;
}

function DownloadTasks({ tasks, api, setTasks }: { tasks: DownloadTask[]; api: <T>(path: string, init?: RequestInit) => Promise<T>; setTasks: React.Dispatch<React.SetStateAction<DownloadTask[]>> }) { useEffect(() => { const timer = window.setInterval(() => { tasks.filter(task => !['completed', 'failed', 'cancelled'].includes(task.status)).forEach(task => api<DownloadTask>(`/api/files/remote-download?task_id=${encodeURIComponent(task.task_id)}`).then(updated => setTasks(current => current.map(item => item.task_id === updated.task_id ? updated : item))).catch(() => undefined)); }, 800); return () => window.clearInterval(timer); }, [api, tasks, setTasks]); return <div className="download-panel"><div className="section-heading"><h2>Cloud downloads</h2><span>Saved directly on the server</span></div>{tasks.slice(0, 3).map(task => <div className="download-row" key={task.task_id}><div><strong>{task.filename}</strong><small>{task.status} {task.error ? `• ${task.error}` : ''}</small></div><span>{task.progress_percent || 0}%</span></div>)}</div>; }

function CloudDownloadDialog({ api, currentFolder, onClose, onStarted, onError }: { api: <T>(path: string, init?: RequestInit) => Promise<T>; currentFolder: string; onClose: () => void; onStarted: (task: DownloadTask) => void; onError: (value: string) => void }) { const [url, setUrl] = useState(''); const [filename, setFilename] = useState(''); const [folder, setFolder] = useState(currentFolder || '/'); const start = async () => { try { const task = await api<DownloadTask>('/api/files/remote-download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, filename: filename || undefined, destination: folder || '/' }) }); onStarted(task); onClose(); } catch (err) { onError(err instanceof Error ? err.message : 'Download could not start'); } }; return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose}><X size={18} /></button><div className="modal-heading"><span className="tile-icon cyan"><CloudDownload size={21} /></span><div><h2>Cloud Web Download</h2><p>Direct download to DhilipHome server</p></div></div><label>Web file URL<input value={url} onChange={event => { setUrl(event.target.value); if (!filename) setFilename(event.target.value.split('/').pop() || ''); }} placeholder="https://example.com/movie.mp4" /></label><label>File name on server<input value={filename} onChange={event => setFilename(event.target.value)} placeholder="movie.mp4" /></label><label>Save to server folder<input value={folder} onChange={event => setFolder(event.target.value)} placeholder="/Downloads" /></label><p className="hint">The server downloads the URL directly. Your browser never carries the file.</p><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!/^https?:\/\//i.test(url)} onClick={start}><CloudDownload size={16} /> Start download</button></div></div></div>; }

function SystemView({ api }: { api: <T>(path: string, init?: RequestInit) => Promise<T> }) { const [metrics, setMetrics] = useState<Metrics | null>(null); const refresh = () => api<Metrics>('/api/system').then(setMetrics).catch(() => undefined); useEffect(() => { refresh(); }, []); return <section><PageTitle title="System diagnostics" subtitle="Live hardware and server telemetry" action={<button className="icon-button" onClick={refresh}><RefreshCw size={18} /></button>} /><div className="metric-grid">{metrics && <><MetricTile label="CPU LOAD" value={`${metrics.cpu.usage_percent}%`} sub={`${metrics.cpu.physical_cores} physical cores`} icon={Cpu} color="violet" percent={metrics.cpu.usage_percent} /><MetricTile label="MEMORY (RAM)" value={`${metrics.memory.usage_percent}%`} sub={`${metrics.memory.used_human} of ${metrics.memory.total_human}`} icon={Activity} color="green" percent={metrics.memory.usage_percent} /><MetricTile label="UPTIME" value={metrics.uptime.server_uptime_human} sub={metrics.operating_system.hostname} icon={Server} color="amber" percent={100} /></>}</div></section>; }
function EmptyState({ label, detail }: { label: string; detail: string }) { return <div className="empty-state"><Folder size={30} /><strong>{label}</strong><span>{detail}</span></div>; }
